# default_config:  <-- Diese Zeile löschen oder auskommentieren
frontend:          # <-- Stattdessen nur das Frontend laden

# https://www.home-assistant.io/integrations/homeassistant/
homeassistant:
  debug: true

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.handballnet: debug